app/models.py
from datetime import datetime

from flask import current_app
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer

from . import db

categories = {
    'nepal': 1,
    'world': 2,
    'business': 4,
    'sports': 8,
    'entertainment': 16,
    'science-technology': 32,
}


class User(db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), unique=True, index=True)
    preferred_time = db.Column(db.String(8), index=True)
    subscriptions = db.Column(db.Integer)
    corona_update = db.Column(db.Boolean, default=False)
    confirmed = db.Column(db.Boolean, default=False)

    def __init__(self, **kwargs):
        super(User, self).__init__(**kwargs)
        if self.subscriptions is None:
            self.subscriptions = 0

    def __repr__(self):
        return f'User {self.email}'

    def add_subscription(self, category):
        if not self.is_subscribed(category):
            self.subscriptions += categories[category]

    def remove_subscription(self, category):
        if self.is_subscribed(category):
            self.subscriptions -= categories[category]

    def is_subscribed(self, category):
        return self.subscriptions & categories[category] == categories[category]

    def list_subscriptions(self):
        subscription_list = list()
        for category in categories:
            if self.is_subscribed(category):
                subscription_list.append(category)
        return subscription_list

    def generate_confirmation_token(self, expiration=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'confirm': self.id}).decode('utf-8')

    @classmethod
    def confirm(cls, token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token.encode('utf-8'))
        except:
            return False

        if not cls.query.filter_by(id=data.get('confirm')):
            return False
        user = cls.query.filter_by(id=data.get('confirm')).first()
        user.confirmed = True
        db.session.add(user)
        return True


class News(db.Model):
    __tablename__='news'
    id = db.Column(db.Integer, primary_key=True)
    headline = db.Column(db.String(128), unique=True)
    url = db.Column(db.String(256))
    summarized_body = db.Column(db.Text())
    category = db.Column(db.String(16))
    date = db.Column(db.DateTime(), default=datetime.utcnow)
    
    def __repr__(self):
        return f'[{self.date}]: {self.headline}'
    

app/__init__.py
from flask import Flask, render_template
from flask_mail import Mail
from flask_sqlalchemy import SQLAlchemy

from config import config

db = SQLAlchemy()
mail = Mail()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    db.init_app(app)
    mail.init_app(app)

    if app.config['SSL_REDIRECT']:
        from flask_sslify import SSLify
        sslify = SSLify(app)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    from .errors import errors as errors_blueprint
    app.register_blueprint(errors_blueprint)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from flask import render_template
from . import main


@main.route('/')
def index():
    return render_template('index.html')


@main.route('/about')
def about():
    return render_template('about.html')

app/templates/about.html
<!DOCTYPE html>

<html>
  <head>
    <title>Minimal News</title>
    <meta charset="utf-8" />
    <link
      rel="stylesheet"
      href="{{ url_for('static',
    filename='css/main.css') }}"
    />
  </head>
  <body class="subpage">
    <!-- Header -->
    <header id="header">
      <nav class="left">
        <a href="#menu"><span>Menu</span></a>
      </nav>
      <a href="{{ url_for('main.index')}}" class="logo">Minimal News</a>
      <nav class="right">
        <a href="{{ url_for('auth.register') }}" class="button alt">Sign Up</a>
      </nav>
    </header>

    <!-- Menu -->
    <nav id="menu">
      <ul class="links">
        <li><a href="{{ url_for('main.index') }}">Home</a></li>
        <li><a href="{{ url_for('main.about') }}">About</a></li>
      </ul>
      <ul class="actions vertical">
        <li><a href="#" class="button fit">Sign Up</a></li>
      </ul>
    </nav>

    <!-- Main -->
    <section id="main" class="wrapper">
      <div class="inner">
        <header class="align-center">
          <h1>About</h1>
          <p>Minimal News Newsletter Service</p>
        </header>
        <div class="image fit">
          <img src="../static/images/pic05.jpg" alt="" />
        </div>
        <p>
          Today's era is truly an era of information overload with News not
          being an exception. It is an important part of people's lives. There
          are so many sites and applications regulating news online. So, it is
          an equally important and difficult task to select the most promising
          and reliable news source on the Internet. Even with a good news
          source, we have to bear with all the advertisements and pop-ups which
          can be annoying and can ruin our reading experience. This is where
          MINIMAL NEWS steps in.
        </p>
        <p>
          MINIMAL NEWS is a web news service that takes an approach different
          from the mainstream media focusing on ‘the need to know’, not
          everything, but ‘what is relevant’. A simple registration will deliver
          minimal curated news to the users’ right to their inbox. No more ads,
          no more getting stuck in an infinite scroll or a rabbit hole of
          hyperlinks so that the user can give their precious attention to the
          tasks that require it while still staying informed.
        </p>
        <p>
          In this era of ‘too much news’, MINIMAL NEWS focuses only on the
          necessary and specific news that a reader wants. Instead of falling on
          a rabbit hole and wasting time on the unnecessary, irrelevant news, a
          reader has the privilege of reading what he wants to read. This will
          not only save time but also prevent the reader to get mentally
          affected by the not needed news.
        </p>
      </div>
    </section>
    <!-- Two -->
    <section id="two" class="wrapper style1 special">
      <div class="inner">
        <header>
          <h2>Our Team</h2>
          <p>Kathmandu University</p>
        </header>
        <div class="flex flex-4">
          <div class="box person">
            <div class="image round">
              <img src="../static/images/team/team.jpg" alt="Person 1" />
            </div>
            <h3>Aashutosh Aryal</h3>
            <p>What to write here</p>
          </div>
          <div class="box person">
            <div class="image round">
              <img src="../static/images/team/team.jpg" alt="Person 2" />
            </div>
            <h3>Sandesh Dahal</h3>
            <p>What to write here</p>
          </div>
          ../static/
          <div class="box person">
            <div class="image round">
              <img src="../static/images/team/team.jpg" alt="Person 3" />
            </div>
            <h3>Shusan Khatiwada</h3>
            <p>What to write here</p>
          </div>
          <div class="box person">
            <div class="image round">
              <img src="../static/images/team/team.jpg" alt="Person 4" />
            </div>
            <h3>Sameer J. Subedi</h3>
            <p>What to write here</p>
          </div>
        </div>
      </div>
    </section>

    <!-- Footer -->
    <footer id="footer">
      <div class="inner">
        <h2>Get In Touch</h2>
        <ul class="actions">
          <li>
            <span class="icon fa-phone"></span>
            <a href="#">(+977) 9841 123456</a>
          </li>
          <li>
            <span class="icon fa-envelope"></span>
            <a href="#">minimalnews@gmail.com</a>
          </li>
          <li>
            <span class="icon fa-map-marker"></span> Baneshwor-10, Kathmandu,
            Nepal
          </li>
        </ul>
      </div>
      <div class="copyright">
        &copy; Minimal News.
      </div>
    </footer>

    <!-- Scripts -->
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery.scrolly.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/skel.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/util.js') }}"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
  </body>
</html>

app/templates/index.html
<!DOCTYPE html>

<html>
  <head>
    <title>Minimal News</title>
    <meta charset="utf-8" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/main.css') }}"
    />
  </head>
  <body>
    <!-- Header -->
    <header id="header">
      <nav class="left">
        <a href="#menu"><span>Menu</span></a>
      </nav>
      <a href="{{ url_for('main.index') }}" class="logo">Minimal News</a>
      <nav class="right">
        <a href="{{ url_for('auth.register') }}" class="button alt">Sign Up</a>
      </nav>
    </header>

    <!-- Menu -->
    <nav id="menu">
      <ul class="links">
        <li><a href="{{ url_for('main.index') }}">Home</a></li>
        <li><a href="{{ url_for('main.about') }}">About</a></li>
      </ul>
      <ul class="actions vertical">
        <li><a href="{{ url_for('auth.register') }}" class="button fit">Sign Up</a></li>
      </ul>
    </nav>

    <!-- Banner -->
    <section id="banner">
      <div class="content">
        <h1>For the need to know</h1>
        <p>
          Everything you need delivered to you.<br />Just the right amount, no
          more, no less.
        </p>
        <ul class="actions">
          <li><a href="#one" class="button scrolly">Get Started</a></li>
        </ul>
      </div>
    </section>

    <!-- One -->
    <section id="one" class="wrapper">
      <div class="inner flex flex-3">
        <div class="flex-item left">
          <div>
            <h3>Fast and Reliable</h3>
            <p>
              Say something about how fast,<br />
              reliable and relevant the news service is.
            </p>
          </div>
          <div>
            <h3>Selectable Scheduiling</h3>
            <p>
              Say about how you can select the time<br />
              convinient for news and updates.
            </p>
          </div>
        </div>
        <div class="flex-item image fit round">
          <img src="../static/images/pic01.jpg" alt="" />
        </div>
        <div class="flex-item right">
          <div>
            <h3>Content Filtering</h3>
            <p>
              Say about wide range of news category<br />
              to select and filter the news from.
            </p>
          </div>
          <div>
            <h3>Variable News Weight</h3>
            <p>
              Say about how much news you want<br />
              and in what format you want them.
            </p>
          </div>
        </div>
      </div>
    </section>

    <!-- Two -->
    <section id="two" class="wrapper style1 special">
      <div class="inner">
        <h2>Newsletter Service</h2>
        <figure>
          <p>
            Subscribe to the Minimal News Newsletter Service to enjoy benefits
            starting today.
          </p>
          <footer>
            <a href="{{ url_for('auth.register') }}" class="button">Sign Up</a> &emsp; &emsp;
            <a href="{{ url_for('main.about') }}" class="button">Learn More</a>
          </footer>
        </figure>
      </div>
    </section>

    <!-- Footer -->
    <footer id="footer">
      <div class="inner">
        <h2>Get In Touch</h2>
        <ul class="actions">
          <li>
            <span class="icon fa-phone"></span>
            <a href="#">(+977) 9841 123456</a>
          </li>
          <li>
            <span class="icon fa-envelope"></span>
            <a href="#">minimalnews@gmail.com</a>
          </li>
          <li>
            <span class="icon fa-map-marker"></span> Baneshwor-10, Kathmandu,
            Nepal
          </li>
        </ul>
      </div>
      <div class="copyright">
        &copy; Minimal News.
      </div>
    </footer>

    <!-- Scripts -->
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery.scrolly.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/skel.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/util.js') }}"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
  </body>
</html>

app/templates/newsletter.html
{% for news in news_obj %}
{% if user.is_subscribed(news.category) %}
<h2>{{ news.headline }}</h2>
<p>{{ news.summarized_body }}</p>
{% endif %}
{% endfor %}

{% if corona_stat and user.corona_update %}
<p>
<strong>Total tests conducted:</strong>{{corona_stat.get('tested_total')}}<br>
<strong>Positive cases:</strong>{{corona_stat.get('tested_positive')}}<br>
<strong>Negative cases:</strong>{{corona_stat.get('tested_negative')}}<br>
<strong>Recovery:</strong>{{corona_stat.get('recovered')}}<br>
<strong>Deaths:</strong>{{corona_stat.get('deaths')}}<br>
<p>
{% endif %}